# Generated by Django 5.0.2 on 2024-02-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_call', models.CharField(max_length=120, null=True)),
                ('name', models.CharField(max_length=26, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=16, null=True)),
                ('alternate_phone', models.CharField(max_length=16, null=True)),
                ('billing_address', models.TextField(null=True)),
                ('member_of_family', models.TextField(null=True)),
                ('worth', models.CharField(max_length=50)),
                ('favourable_apps', models.TextField(null=True)),
            ],
        ),
    ]
