# Generated by Django 5.0.2 on 2024-02-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customer_detail_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
