# Generated by Django 5.0.2 on 2024-02-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customer_detail_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
