# Generated by Django 5.0.2 on 2024-02-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customer_detail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='next_followup',
            field=models.DateTimeField(null=True),
        ),
    ]
