# Generated by Django 5.0.2 on 2024-02-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_customer_detail_notes_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='Notes',
            new_name='content',
        ),
    ]
