# Generated by Django 5.0.2 on 2024-02-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_notes_notes_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='content',
            new_name='notepad',
        ),
    ]
