# Generated by Django 5.0.2 on 2024-02-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminders',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
